version: "3.9"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "10"

services:

  # ======================================================================
  # NGINX reverse proxy
  # ======================================================================

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-certs:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging: *default-logging
    networks:
      - proxy

  nginx-proxy-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    restart: unless-stopped
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging: *default-logging
    networks:
      - proxy

  nginx-proxy-acme:
    image: nginxproxy/acme-companion:2.2
    container_name: nginx-proxy-acme
    restart: unless-stopped
    volumes_from:
      - nginx-proxy
    volumes:
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: $EMAIL
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen
    logging: *default-logging
    networks:
      - proxy

networks:
  proxy:
    name: nginx-proxy

volumes:
  nginx-conf:
  nginx-vhost:
  nginx-certs:
  nginx-acme:
